version: 2
jobs: 
  build:
    working_directory: ~/myapp
    docker:
      - image: circle/node:12-browsers
    steps:
      - checkout:
      path: ~/myapp
      - restore_cache:
          key: angular-wishlist-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: angular-wishlist-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --progress=false --watch=false --browser=ChromeHeadlessCI